### ISSUE TITLE
Can you put a three.js example.

### ISSUE THREAD

**Issue by kordou** [alanross/AlvaAR#4]
Hi, thanks for this great lib,

i am trying to run the THREE..Js but i can unresolved promish..

    this.alva = await AlvaAR.Initialize(this.THREE);
    this.applyPose = AlvaARConnectorTHREE.Initialize(this.THREE);

    this.addToAnimLoop(() => {
      this.imageData = ctx.getImageData(0, 0, this.width, this.height);
      this.pose = alva.findCameraPose(this.imageData);

      if (this.pose)
        this.applyPose(this.pose, this.camera.quaternion, this.camera.position);
    });

could you write a simple three.js with a cube in order to understant the setup ? 

thank you

**Comment by alanross** [comment]
@kordou Have you had a look at the examples [here](https://github.com/alanross/AlvaAR/tree/main/examples/public)?
